grid_map:
  FREE_SPACE: 0
  OBSTACLE: 1

default_map_size: 10
default_num_agents: 4
max_map_size: 100
max_num_agents: 72

ind_reward_func:
  'move': -0.075
  'stay_on_goal': 0
  'stay_off_goal': -0.075
  'collision': -0.5
  'reach_goal': 3

lambda_r: 0.9

fov_size: [9, 9]
K_obs: 3

action_mapping:
  0: [-1, 0]
  1: [1, 0]
  2: [0, -1]
  3: [0, 1]
  4: [0, 0]
action_dim: 5

hidden_channels: 128
num_heads: 2
hidden_dim: 256

# Add parameters related to hierarchical planning
hierarchical_planning:
  num_buckets: 3  # Number of buckets for grouping agents based on heuristic similarity
  coordination_strategy: "hierarchical"  # Strategy for coordinating agents (e.g., hierarchical, flat)
  hierarchical_levels:
    - name: "high_level"
      type: "group_agents"
      parameters:
        threshold: 0.5  # Similarity threshold for grouping agents
    - name: "mid_level"
      type: "coordinate_groups_to_goal_state"
      parameters:
        goal_state: [10, 10]  # Goal state for coordinating groups
    - name: "low_level"
      type: "coordinate_agents_within_group"
      parameters:
        coordination_method: "A*"
        heuristic_type: "euclidean"  # Heuristic function for A* search